services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    # map container 3306 to host 3307 to avoid conflicts with local MySQL
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  auth:
    build:
      context: .
      dockerfile: cmd/auth/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: password
      DB_NAME: ecommerce
    ports:
      - "8080:8080"
    depends_on:
      - db

  product:
    build:
      context: .
      dockerfile: cmd/product/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: password
      DB_NAME: ecommerce
    ports:
      - "8081:8081"
    depends_on:
      - db

  transaction:
    build:
      context: .
      dockerfile: cmd/transaction/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASS: password
      DB_NAME: ecommerce
    ports:
      - "8082:8082"
    depends_on:
      - db

volumes:
  db_data:
